### ISSUE TITLE
Add greetings in discord bot

### ISSUE THREAD

**Issue by joeyouss** [Codess-Cafe/Python-discord-bot#1]
Add normal greetings like if I tier hi, hello in the chat , my discord bot should reply with greetings too

**Comment by zerru14** [comment]
I'd like to work on it.

**Comment by joeyouss** [comment]
Hi, sorry to inform this project is only for mentees of codess.cafe

**Comment by zerru14** [comment]
oh. Okay.

**Comment by sanyagoyal2000** [comment]
I would like to work on this issue

**Comment by sanyagoyal2000** [comment]
I would like to work on this issue.

**Comment by SangeetaMishra** [comment]
Hi. I would like to take this issue.

**Comment by joeyouss** [comment]
@SangeetaMishra can you tell the status of PR?

**Comment by SangeetaMishra** [comment]
@joeyouss Working on it.

**Comment by joeyouss** [comment]
do you need any help ?

**Comment by SangeetaMishra** [comment]
Thanks for asking! I was able to make the changes. Please review it.
